server:
  port: 8080
  servlet:
    context-path: /
eureka:
  client:
    enabled: false

billing:
  url: "http://billing.pas-mini.io"
  authentication: "Basic YmlsbGluZ0B1ZW5naW5lLm9yZzoxODkyNXVuZw=="

---
server:
  port: 9091

spring:
  profiles: local
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: docker-cluster
      host: 13.125.185.128
      port: 9200
  cloud:
    stream:
      kafka:
        binder:
          brokers: 52.79.164.208:9092
      bindings:
        billing-target:
          group: ${spring.application.name}
          destination: billing
        billing-source:
          destination: billing
        metering-sub:
          group: ${spring.application.name}
          destination: metering
---
server:
  port: 8080

spring:
  profiles: docker
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: docker-cluster
      host: 13.125.185.128
      port: 9200
  cloud:
    stream:
      kafka:
        binder:
          brokers: 52.79.164.208:9092
      bindings:
        billing-target:
          group: ${spring.application.name}
          destination: billing
        billing-source:
          destination: billing
        metering-sub:
          group: ${spring.application.name}
          destination: metering